# Generated by Django 5.2.15 on 2026-06-22 22:26

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pk', models.CharField(max_length=50)),
                ('post_kind', models.IntegerField(choices=[(1, 'Photo'), (2, 'Video'), (3, 'Album')])),
                ('caption', models.TextField(blank=True, null=True)),
                ('short_code', models.CharField(max_length=50)),
                ('taken_at', models.DateTimeField()),
                ('is_media_saved', models.BooleanField(default=False)),
                ('is_comment_saved', models.BooleanField(default=False)),
                ('interval', models.IntegerField(choices=[(1, 'Before'), (2, 'Current'), (3, 'After')])),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.page')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('left_at', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=posts.models.post_path)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.page')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
