# Generated by Django 5.2.15 on 2026-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_kind',
            field=models.IntegerField(blank=True, choices=[(1, 'Photo'), (2, 'Video'), (3, 'Album')], null=True),
        ),
    ]
