# Generated by Django 5.2.15 on 2026-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_related',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
